palette = "catppuccin_mocha"

format = """
$os$username$hostname$directory \
$fill\
$cmd_duration\
$fill  \
$python\
$rust\
$nodejs\
$bun\
$kotlin\
$all\
$line_break\
$character"""
# right_format = """$all"""
command_timeout = 1000
add_newline = true

[fill]
style = 'fg:current_line'
symbol = ' '

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Shows the OS
[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

# Shows the username
[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true


# Shows the hostname
[hostname]
ssh_only = true
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current directory
[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = ' [$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
format = ' [$duration]($style) '
min_time = 500

# Shows current git branch
[git_branch]
format = '[$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
ahead = '[⬆](bold purple) '
behind = '[⬇](bold purple) '
staged = '[✚](green) '
deleted = '[✖](red) '
renamed = '[➜](purple) '
stashed = '[✭](cyan) '
untracked = '[◼](white) '
modified = '[✱](blue) '
conflicted = '[═](yellow) '
diverged = '⇕ '
up_to_date = ''

[kotlin]
symbol = ''

[nodejs]
symbol = ''


[python]
symbol = ''


[rust]
symbol = ''


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
